In [16]:
import pandas as pd

In [17]:
df = pd.read_csv(
    'datasets_treino_pandas.csv'
)

df[:5]

,ID_Pedido,Data_Pedido,ID_Cliente,Segmento,Regiao,Categoria,Produto,Valor_Venda,Quantidade,Desconto,Lucro
0,OD-1164,2024-09-06,CT-154,Home Office,Sul,Vestuário,Calça Jeans Premium,1123.27,10,0.0,280.82
1,OD-1065,2025-05-27,CT-140,Corporativo,Nordeste,Material de Escritório,Organizador de Mesa,252.15,6,0.0,100.86
2,OD-1049,31/07/2024,CT-181,Consumidor,Nordeste,Material de Escritório,Organizador de Mesa,79.36,2,0.0,31.74
3,OD-1243,2026-02-27,CT-228,Corporativo,Norte,Material de Escritório,Caneta Gel 12un,135.26,8,0.1,41.93
4,OD-1157,2026-03-10,CT-213,Corporativo,Centro-Oeste,Eletrônicos,Smartphone X,10522.96,9,0.0,1578.44

In [18]:
#function date standardization 

def standardizesDates(dataframe, column_name):
    dataframe[column_name] = pd.to_datetime(dataframe[column_name], format='mixed', dayfirst=True);
    return dataframe

In [19]:
df = standardizesDates(df,'Data_Pedido')

df['Data_Pedido']

0     2024-09-06
1     2025-05-27
2     2024-07-31
3     2026-02-27
4     2026-03-10
         ...
505   2024-05-18
506   2024-06-14
507   2025-08-28
508   2024-01-15
509   2025-03-24
Name: Data_Pedido, Length: 510, dtype: datetime64[ns]

In [20]:
df['Desconto'] = df['Desconto'].fillna('Desconto não aplicado')
df['Lucro'] = df['Lucro'].replace('Sem lucro', '0')
df.isna().sum()

ID_Pedido       0
Data_Pedido     0
ID_Cliente      0
Segmento        0
Regiao          0
Categoria       0
Produto         0
Valor_Venda     0
Quantidade      0
Desconto        0
Lucro          24
dtype: int64

In [21]:
df['Lucro'] = pd.to_numeric(df['Lucro'], errors='coerce')
df['Valor_Venda'] = pd.to_numeric(df['Valor_Venda'], errors='coerce')

df['Custo'] = df['Valor_Venda'] - df['Lucro'];
print(df[['Custo', 'Valor_Venda', 'Lucro']]);

       Custo  Valor_Venda    Lucro
0     842.45      1123.27   280.82
1     151.29       252.15   100.86
2      47.62        79.36    31.74
3      93.33       135.26    41.93
4    8944.52     10522.96  1578.44
..       ...          ...      ...
505  1122.98      1497.31   374.33
506   566.55       651.21    84.66
507      NaN       110.34      NaN
508   134.56       224.27    89.71
509   395.25       501.90   106.65

[510 rows x 3 columns]

In [22]:
#Sinalizador de rentabilidade

df['Alta_Rentabilidade'] = df['Lucro'] > 200
df['Alta_Rentabilidade']

0       True
1      False
2      False
3      False
4       True
       ...
505     True
506    False
507    False
508    False
509    False
Name: Alta_Rentabilidade, Length: 510, dtype: bool

In [23]:
MaioresLucros = df.groupby('Produto')['Lucro'].sum().nlargest(5)
MaioresLucros

Produto
Notebook Pro          61386.90
Monitor 4K            32434.83
Smartphone X          21328.54
Mesa de Escritório    15029.18
Cadeira Ergonômica     7830.34
Name: Lucro, dtype: float64

In [24]:
#Margens negarivas

df_margens_negativas = df.query('Lucro < 0')
df_margens_negativas

Empty DataFrame
Columns: [ID_Pedido, Data_Pedido, ID_Cliente, Segmento, Regiao, Categoria, Produto, Valor_Venda, Quantidade, Desconto, Lucro, Custo, Alta_Rentabilidade]
Index: []

In [26]:
#Filtragem complexa

df_filtrado = df.query("Segmento == 'Consumidor' and Regiao == 'Sudeste' and Categoria == 'Vestuário'")
df_filtrado

,ID_Pedido,Data_Pedido,ID_Cliente,Segmento,Regiao,Categoria,Produto,Valor_Venda,Quantidade,Desconto,Lucro,Custo,Alta_Rentabilidade
69,OD-1270,2025-07-26,CT-224,Consumidor,Sudeste,Vestuário,Tênis Casual,1125.75,6,0.0,281.44,844.31,True
75,OD-1047,2024-05-28,CT-108,Consumidor,Sudeste,Vestuário,Tênis Casual,924.35,5,0.0,231.09,693.26,True
144,OD-1197,2024-09-05,CT-229,Consumidor,Sudeste,Vestuário,Calça Jeans Premium,455.95,4,0.0,113.99,341.96,False
239,OD-1084,2025-10-09,CT-236,Consumidor,Sudeste,Vestuário,Camiseta Algodão,104.40,2,0.0,26.10,78.30,False
282,OD-1414,2024-06-20,CT-174,Consumidor,Sudeste,Vestuário,Camiseta Algodão,91.50,2,0.0,22.88,68.62,False
284,OD-1267,2024-12-15,CT-217,Consumidor,Sudeste,Vestuário,Calça Jeans Premium,978.28,8,0.0,244.57,733.71,True
303,OD-1238,2025-11-02,CT-248,Consumidor,Sudeste,Vestuário,Camiseta Algodão,97.25,2,0.15,13.37,83.88,False
310,OD-1390,2025-10-06,CT-123,Consumidor,Sudeste,Vestuário,Tênis Casual,821.70,4,0.0,205.42,616.28,True
404,OD-1212,2026-02-23,CT-109,Consumidor,Sudeste,Vestuário,Camiseta Algodão,245.55,5,0.1,42.97,202.58,False
442,OD-1238,2025-11-02,CT-248,Consumidor,Sudeste,Vestuário,Camiseta Algodão,97.25,2,0.15,13.37,83.88,False
490,OD-1219,2024-07-23,CT-220,Consumidor,Sudeste,Vestuário,Calça Jeans Premium,752.18,6,0.05,159.84,592.34,False

In [33]:
# Tabelas dinamicas
df['Categoria'] = df['Categoria'].str.strip()
pivot_table = pd.pivot_table(
    df,
    index='Categoria',
    columns='Regiao',
    values='Quantidade',
    aggfunc='sum',
    fill_value=0
)

pivot_table

Regiao                  Centro-Oeste  Nordeste  Norte  Sudeste  Sul
Categoria
Eletrônicos                      194       144    148      180  125
Material de Escritório           231       192    231      169  146
Móveis                            89       134     77       89  114
Vestuário                         87        72     94      104  146

In [44]:
#Melhor Cliente
df_cliente = df.groupby(['ID_Cliente', 'Segmento'])['Valor_Venda'].sum().sort_values(ascending=False).reset_index()

df_cliente.iloc[0]

ID_Cliente          CT-115
Segmento       Home Office
Valor_Venda        66077.5
Name: 0, dtype: object

In [54]:
#Produtos unicos

produto_unicos = df['Produto'].value_counts() == 1
df_unicos = df[df['Produto'].isin(produto_unicos)]
df_unicos

Empty DataFrame
Columns: [ID_Pedido, Data_Pedido, ID_Cliente, Segmento, Regiao, Categoria, Produto, Valor_Venda, Quantidade, Desconto, Lucro, Custo, Alta_Rentabilidade]
Index: []